import { SIGUSR1 } from "constants";

export default {
  urls: {
    startSession: "/index/api/v1/startsession",
    category: "/index/api/v1/category",
    baseUrl: "http://localhost:3000",
    subCategory: "/shopping/api/v1/subcategory",
    sortByMethod: "/shopping/api/v1/sort_by_method",
    AllItems: "/shopping/api/v1/get-all-items",
    addToCart: "/payment/api/v1/add_to_cart",
    proceedToCheckout: "/payment/api/v1/proceed-to-checkout",
    checkCart: "/payout/api/v1/cart-checkout",
    payment: "/payout/api/v1/confirm-checkout",
    profileMain: "/profile/api/v1/get-profile",
    profileName: "/profile/api/v1/read-write-name",
    profileEmail: "/profile/api/v1/save-email",
    requestNumber: "/payout/api/v1/phonenumber-request",
    liveLocation: "/profile/api/v1/live-location",
    autoMessagePayment: "/auto-message/api/v1/payment-state",
    autoMessageRating: "/auto-message/api/v1/rating",
    autoPaymentReconciliation: `/auto-message/api/v1/payment-reconciliation`,
    profileSectionRedirector: `/profile/api/v1/redirector`,
  },

  urlsIds: {
    categoryId: "s1",
    subCategoryId: "s2",
    sortByMethodId: "s3",
    AllItemsId: "s4",
    addToCartId: "s5",
    proceedToCheckoutId: "s6",
    checkCartId: "pd1",
    paymentId: "pd2",
    requestNumberId: "pd3",
    profileMainId: "p1",
    profileNameId: "qa2",
    profileEmailId: "qa3",
    liveLocationId: "qa4",
    autoMessagePaymentId: "amp2",
    autoMessageRatingId: "amr2",
    autoPaymentReconciliationId: "amp3",
    profileSectionRedirectorId: "pr",
  },
  twilio: {
    accountSid: process.env.TWILIO_ACCOUNT_SID,
    accountToken: process.env.TWILIO_ACCOUNT_TOKEN,
  },
};
